// Auto-generated environment configuration
// Generated on: 2025-09-26T07:28:31.292Z
// Source: /home/deachawat/dev/projects/BPP/PK/.env
// DO NOT EDIT - This file is automatically generated from .env

export const environment = {
  "production": false,
  "apiUrl": "/api",
  "backendUrl": "http://127.0.0.1:7070",
  "bridgeServiceUrl": "http://127.0.0.1:5000",
  "frontendPort": 6060,
  "backendPort": 7070,
  "bridgeServicePort": 5000,
  "primaryDatabase": "TFCPILOT3",
  "scaleDatabase": "TFCPILOT3",
  "jwtTokenKey": "pk_auth_token",
  "sessionTimeout": 604800000,
  "defaultScaleBaudRate": 9600,
  "weightPollingInterval": 400,
  "websocketMaxResponseTime": 100,
  "features": {
    "multiScaleSupport": true,
    "autoScaleDetection": true,
    "sessionTimeout": true,
    "connectionMonitoring": true,
    "accessibility": true,
    "animations": true
  },
  "logging": {
    "level": "debug",
    "enableConsoleLog": true,
    "enableApiLog": true
  },
  "ui": {
    "theme": "nwfth-brown",
    "animationsEnabled": true,
    "touchOptimized": true,
    "minTouchTargetSize": 44
  },
  "app": {
    "name": "Partial Picking System",
    "version": "1.0.0",
    "company": "Newly Weds Foods Thailand"
  }
};
